config/routes.rb
JRE::Application.routes.draw do
  
  get "google_map/map"

  root :to => 'static_pages#home'

  get "services", to: "static_pages#services", as: :services

  get "projects", to: "static_pages#projects", as: :projects

  get "profile", to: "static_pages#profile", as: :profile

  get "contact", to: "static_pages#contact", as: :contact

  get "map", to: "google_map#map", as: :map

end

app/models/google_map.rb
class GoogleMap < ActiveRecord::Base
  # attr_accessible :title, :body

  acts_as_gmappable

    # def gmaps4rails_address
    # #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    #   "#{self.street}, #{self.city}, #{self.country}" 
    # end

    # add_column :users, :latitude,  :float #you can change the name, see wiki
    # add_column :users, :longitude, :float #you can change the name, see wiki
    # add_column :users, :gmaps, :boolean #not mandatory, see wiki
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/google_map_controller.rb
class GoogleMapController < ApplicationController
  def map
  end
  @json = User.all.to_gmaps4rails do |user, marker|
  marker.infowindow render_to_string(:partial => "/users/my_template", :locals => { :object => user})
  marker.picture({
                  :picture => "http://www.blankdots.com/img/github-32x32.png",
                  :width   => 32,
                  :height  => 32
                 })
  marker.title   "i'm the title"
  marker.sidebar "i'm the sidebar"
  marker.json({ :id => user.id, :foo => "bar" })
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def services
  end

  def projects
  end

  def profile
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/google_map_helper.rb
module GoogleMapHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/google_map/map.html.erb
<!-- create html + load js files but don't create map itself: will be done after ajax call -->
<%= gmaps({:last_map => false}) %>
 
<!--  button to trigger ajax call -->
<button type="button" id="ajax">Load Map</button>
 
<script type="text/javascript" charset="utf-8">
$(function() {
 
//hide the empty container
$(".map_container").hide();
 
$("#ajax").click(function(){
 
  $.getJSON('/users', function(json){
    $(".map_container").show();
    Gmaps.loadMaps();
    Gmaps.map.addMarkers(json);
  })
  })
 
});
</script>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "JRE", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to t(:servies), services_path %></li>
      <li><%= link_to t(:projects), projects_path %></li>
      <li><%= link_to t(:profile), profile_path %></li>
      <li><%= link_to t(:contact), contact_path %></li>
      <li><%= link_to t(:map), map_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Select Language <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="?locale=en">English</a></li>
          <li><a href="?locale=es">Español</a></li> -->
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </nav> 

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <title>JRE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag 'gmaps4rails' %>
    <%= javascript_include_tag "gmaps4rails" %>
    <%= yield :scripts %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>  
    <div class='container'>  
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1> Jim Riley Engineering </h1>
<h3> Specializing in Water Rights </h3> 
  <p>
    Jim Riley Engineering, LC (JRE) is a water right engineering consulting firm in Utah. JRE provides specialization in change applications, updating titles on water rights, research, conflict resolution, enforcement action, diligence claims, nonuse applications, applications to appropriate, proofs of beneficial use and much more.
  </br>
  </br>
    JRE has more than 30 years of experience in water rights and has to provide clients with personal, honest, ethical, and cost effective service in a timely manner.
  </p>  

app/views/static_pages/profile.html.erb
<h1>StaticPages#profile</h1>
<p>Find me in app/views/static_pages/profile.html.erb</p>

app/views/static_pages/projects.html.erb
<h1>StaticPages#projects</h1>
<p>Find me in app/views/static_pages/projects.html.erb</p>

app/views/static_pages/services.html.erb
<h1>StaticPages#services</h1>
<p>Find me in app/views/static_pages/services.html.erb</p>